name: Terraform CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    strategy:
      matrix:
        path:
         - architectures/apigw-nlb-ec2
         - architectures/apigw-nlb-ecs
         - architectures/apigw-public-ec2
         - architectures/cloudmap-vpn-ecs
         - architectures/vanilla-ec2
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       working-directory: ${{ matrix.path }}
       id: init
       run: terraform init

     - name: Terraform format
       working-directory: ${{ matrix.path }}
       id: fmt
       run: terraform fmt -check

     - name: Terraform validate
       working-directory: ${{ matrix.path }}
       id: validate
       run: terraform validate
